## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: 58572514dec0230a1aac09e4c4e9d60a

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
NULL

## This section of code is only included where templated classes are
## included.  Don't rely on the approach taken here, as it may change
## soon.
check_type <- function(type, valid) {
  i <- match(list(type), valid, nomatch=NA)
  if (is.na(i)) {
    choices <- paste(sprintf("\t%s", sapply(valid, paste, collapse=", ")),
                     collapse="\n")
    stop(sprintf("Invalid type '%s'; expected one of:\n%s",
                 paste(type, collapse=", "), choices))
  }
  names(valid)[[i]]
}

##' @title Lorenz ODE system s
##' @param sigma model parameter
##' @param R model parameter
##' @param b model parameter
##' @export
`Lorenz` <- function(sigma, R, b) {
  Lorenz__ctor(sigma, R, b)
}

.R6_Lorenz <-
  R6::R6Class(
    "Lorenz",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      ode_size = function(value) {
        if (missing(value)) {
          Lorenz__ode_size__get(self)
        } else {
          stop("Lorenz$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Lorenz__ode_state__get(self)
        } else {
          Lorenz__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Lorenz__ode_rates__get(self)
        } else {
          stop("Lorenz$ode_rates is read-only")
        }
      },
      pars = function(value) {
        if (missing(value)) {
          Lorenz__pars__get(self)
        } else {
          stop("Lorenz$pars is read-only")
        }
      }))

##' @title Create lorenz solver to step lorenz system
##' @param T type of system
##' @param control object
##' @export
lorenzRunner <- function(T) {
  type <- c(T)
  valid <- list("lorenzRunner<Lorenz>"="Lorenz")
  constructors <- list("lorenzRunner<Lorenz>"=`lorenzRunner<Lorenz>`)
  constructors[[check_type(type, valid)]]
}
.R6_lorenzRunner <- R6::R6Class("lorenzRunner")


`lorenzRunner<Lorenz>` <- function(obj, control=OdeControl()) {
  lorenzRunner___Lorenz__ctor(obj, control)
}
.R6_lorenzRunner___Lorenz <-
  R6::R6Class(
    "lorenzRunner<Lorenz>",
    inherit=.R6_lorenzRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      advance_adaptive = function(time) {
        lorenzRunner___Lorenz__advance_adaptive(self, time)
      },
      advance_fixed = function(time) {
        lorenzRunner___Lorenz__advance_fixed(self, time)
      },
      step = function() {
        lorenzRunner___Lorenz__step(self)
      },
      step_to = function(time) {
        lorenzRunner___Lorenz__step_to(self, time)
      },
      set_state = function(y, time) {
        lorenzRunner___Lorenz__set_state(self, y, time)
      },
      set_state_from_system = function() {
        lorenzRunner___Lorenz__set_state_from_system(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          lorenzRunner___Lorenz__time__get(self)
        } else {
          stop("lorenzRunner<Lorenz>$time is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          lorenzRunner___Lorenz__state__get(self)
        } else {
          stop("lorenzRunner<Lorenz>$state is read-only")
        }
      },
      times = function(value) {
        if (missing(value)) {
          lorenzRunner___Lorenz__times__get(self)
        } else {
          stop("lorenzRunner<Lorenz>$times is read-only")
        }
      },
      object = function(value) {
        if (missing(value)) {
          lorenzRunner___Lorenz__object__get(self)
        } else {
          stop("lorenzRunner<Lorenz>$object is read-only")
        }
      }))

##' Control parameters for the ode system
##' @title ODE Control parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
##' @export
`OdeControl` <- function(..., values=list(...)) {
  ret <- OdeControl__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}


