


```{r}
devtools::install()

library(odestepper)
setwd(here::here("inst/examples/lorenz"))

Rcpp::sourceCpp("src/main.cpp",
  verbose = TRUE, rebuild = TRUE
)

# check works
system.time(x <- get_number())

length(x)
```

Compare speed to desolve (with Rcpp)

```{r}
library(deSolve)

lorenz_rhs_r <- function(t, state, pars) {
  with(as.list(c(state, pars)), {
    dx <- sigma * (y - x)
    dy <- x * (rho - z) - y
    dz <- x * y - beta * z
    list(c(dx, dy, dz))
  })
}

# solve Lorenz system with deSolve + RK45 via Rcpp
desolve_time1 <- system.time({
  sol_desolve1 <- ode(
    y = c(x = 1, y = 1, z = 1),
    times = x,
    func = lorenz_rhs_r,
    parms = c(sigma = 10, rho = 28, beta = 8 / 3),
    method = "ode45"
  )
})

# solve Lorenz system with deSolve + RK45 via Rcpp
desolve_time2 <- system.time({
  sol_desolve2 <- ode(
    y = c(x = 1, y = 1, z = 1),
    times = x,
    func = lorenz_rhs,
    parms = c(sigma = 10, rho = 28, beta = 8 / 3),
    method = "ode45"
  )
})

desolve_time1
desolve_time2

nrow(sol_desolve1)
nrow(sol_desolve2)

# quick visual check
i <- 1:10000
plot(sol_desolve2[i, "x"], sol_desolve2[i, "z"],
  type = "l",
  xlab = "x", ylab = "z", main = "Lorenz attractor (deSolve, RK45)"
)
```

Run just Lorenz

System
```{r}
lz <- Lorenz$new(sigma = 10, R = 28, b = 8 / 3)

lz$pars() # c(10, 28, 8/3)
lz$set_state(c(1, 1, 1)) # sets y0,y1,y2 and updates rates
lz$state() # current state
lz$rates() # current dy/dt

```

Solver

```{r}
# Suppose you have something like:
# lorenz_xp   <- Lorenz_new(y0 = c(1, 0, 0), sigma = 10, R = 28, b = 8/3)
# control_xp  <- OdeControl_new(dt = 0.01, tmax = 50, atol = 1e-8, rtol = 1e-8)


ctrl <- OdeControl_new(
  tol_abs = 1e-8,
  tol_rel = 1e-8,
  a_y = 1.0,
  a_dydt = 1.0,
  step_size_min = 1e-8,
  step_size_max = 0.1,
  step_size_initial = 1e-3
)

runner <- Runner$new(lz$ptr, ctrl)

runner$set_state_from_system()
runner$advance_adaptive(10)
runner$time()
runner$state()

runner$advance_fixed(seq(10, 20, by = 0.1))
runner$times()
runner$state()
```
