// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _PLANT_RCPPR6_POST_HPP_
#define _PLANT_RCPPR6_POST_HPP_

#include <Rcpp.h>
#include <plant/RcppR6_support.hpp>

namespace plant {
namespace RcppR6 {
namespace traits {
template <> inline std::string   class_name_r<plant::ode::test::Lorenz >() {return "Lorenz";}
template <> inline std::string   package_name<plant::ode::test::Lorenz >() {return "plant";}
template <> inline std::string generator_name<plant::ode::test::Lorenz >() {return ".R6_Lorenz";}
template <> inline std::string   class_name_r<plant::ode::test::OdeR >() {return "OdeR";}
template <> inline std::string   package_name<plant::ode::test::OdeR >() {return "plant";}
template <> inline std::string generator_name<plant::ode::test::OdeR >() {return ".R6_OdeR";}
template <> inline std::string   class_name_r<plant::ode::Runner<plant::ode::test::Lorenz> >() {return "OdeRunner<Lorenz>";}
template <> inline std::string   package_name<plant::ode::Runner<plant::ode::test::Lorenz> >() {return "plant";}
template <> inline std::string generator_name<plant::ode::Runner<plant::ode::test::Lorenz> >() {return ".R6_OdeRunner___Lorenz";}

template <> inline std::string   class_name_r<plant::ode::Runner<plant::ode::test::OdeR> >() {return "OdeRunner<OdeR>";}
template <> inline std::string   package_name<plant::ode::Runner<plant::ode::test::OdeR> >() {return "plant";}
template <> inline std::string generator_name<plant::ode::Runner<plant::ode::test::OdeR> >() {return ".R6_OdeRunner___OdeR";}
template <> inline std::string   class_name_r<plant::ode::OdeControl >() {return "OdeControl";}
template <> inline std::string   package_name<plant::ode::OdeControl >() {return "plant";}
template <> inline std::string generator_name<plant::ode::OdeControl >() {return "";}
}
}
}

namespace Rcpp {
template <typename T>
SEXP wrap(const plant::RcppR6::RcppR6<T>& x) {
  return x.to_R6();
}

namespace traits {
template <typename T>
class Exporter<plant::RcppR6::RcppR6<T> > {
public:
  Exporter(SEXP x) : obj(plant::RcppR6::RcppR6<T>(x)) {}
  inline plant::RcppR6::RcppR6<T> get() { return obj; }
private:
  plant::RcppR6::RcppR6<T> obj;
};
}

template <> inline SEXP wrap(const plant::ode::test::Lorenz& x) {
  return wrap(plant::RcppR6::RcppR6<plant::ode::test::Lorenz>(x));
}
template <> inline plant::ode::test::Lorenz as(SEXP x) {
  return *(plant::RcppR6::RcppR6<plant::ode::test::Lorenz>(x));
}
template <> inline SEXP wrap(const plant::ode::test::OdeR& x) {
  return wrap(plant::RcppR6::RcppR6<plant::ode::test::OdeR>(x));
}
template <> inline plant::ode::test::OdeR as(SEXP x) {
  return *(plant::RcppR6::RcppR6<plant::ode::test::OdeR>(x));
}
template <> inline SEXP wrap(const plant::ode::Runner<plant::ode::test::Lorenz>& x) {
  return wrap(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> >(x));
}
template <> inline plant::ode::Runner<plant::ode::test::Lorenz> as(SEXP x) {
  return *(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> >(x));
}

template <> inline SEXP wrap(const plant::ode::Runner<plant::ode::test::OdeR>& x) {
  return wrap(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> >(x));
}
template <> inline plant::ode::Runner<plant::ode::test::OdeR> as(SEXP x) {
  return *(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> >(x));
}
template <> inline SEXP wrap(const plant::ode::OdeControl& x) {
  Rcpp::List ret;
  ret["tol_abs"] = Rcpp::wrap(x.tol_abs);
  ret["tol_rel"] = Rcpp::wrap(x.tol_rel);
  ret["a_y"] = Rcpp::wrap(x.a_y);
  ret["a_dydt"] = Rcpp::wrap(x.a_dydt);
  ret["step_size_min"] = Rcpp::wrap(x.step_size_min);
  ret["step_size_max"] = Rcpp::wrap(x.step_size_max);
  ret["step_size_initial"] = Rcpp::wrap(x.step_size_initial);
  ret.attr("class") = "OdeControl";
  return ret;
}
template <> inline plant::ode::OdeControl as(SEXP x) {
  if (!plant::RcppR6::is<plant::ode::OdeControl >(x)) {
    Rcpp::stop("Expected an object of type OdeControl");
    // NOTE: Won't drop through or return anything.
  }
  // NOTE: assumes default constructable, and will assign *every*
  // field twice.  No current support for a hook.
  plant::ode::OdeControl ret;
  Rcpp::List xl(x);
  // ret.tol_abs = Rcpp::as<decltype(rettol_abs) >(xl["tol_abs"]);
  ret.tol_abs = Rcpp::as<double >(xl["tol_abs"]);
  // ret.tol_rel = Rcpp::as<decltype(rettol_rel) >(xl["tol_rel"]);
  ret.tol_rel = Rcpp::as<double >(xl["tol_rel"]);
  // ret.a_y = Rcpp::as<decltype(reta_y) >(xl["a_y"]);
  ret.a_y = Rcpp::as<double >(xl["a_y"]);
  // ret.a_dydt = Rcpp::as<decltype(reta_dydt) >(xl["a_dydt"]);
  ret.a_dydt = Rcpp::as<double >(xl["a_dydt"]);
  // ret.step_size_min = Rcpp::as<decltype(retstep_size_min) >(xl["step_size_min"]);
  ret.step_size_min = Rcpp::as<double >(xl["step_size_min"]);
  // ret.step_size_max = Rcpp::as<decltype(retstep_size_max) >(xl["step_size_max"]);
  ret.step_size_max = Rcpp::as<double >(xl["step_size_max"]);
  // ret.step_size_initial = Rcpp::as<decltype(retstep_size_initial) >(xl["step_size_initial"]);
  ret.step_size_initial = Rcpp::as<double >(xl["step_size_initial"]);
  return ret;
}
}

#endif
