// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// System_new
SEXP System_new(double sigma, double R, double b);
RcppExport SEXP _odelia_System_new(SEXP sigmaSEXP, SEXP RSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(System_new(sigma, R, b));
    return rcpp_result_gen;
END_RCPP
}
// System_pars
Rcpp::NumericVector System_pars(SEXP system_xp);
RcppExport SEXP _odelia_System_pars(SEXP system_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(System_pars(system_xp));
    return rcpp_result_gen;
END_RCPP
}
// System_set_params
void System_set_params(SEXP system_xp, Rcpp::NumericVector params);
RcppExport SEXP _odelia_System_set_params(SEXP system_xpSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type params(paramsSEXP);
    System_set_params(system_xp, params);
    return R_NilValue;
END_RCPP
}
// System_set_state
void System_set_state(SEXP system_xp, Rcpp::NumericVector y, double time);
RcppExport SEXP _odelia_System_set_state(SEXP system_xpSEXP, SEXP ySEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    System_set_state(system_xp, y, time);
    return R_NilValue;
END_RCPP
}
// System_state
Rcpp::NumericVector System_state(SEXP system_xp);
RcppExport SEXP _odelia_System_state(SEXP system_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(System_state(system_xp));
    return rcpp_result_gen;
END_RCPP
}
// System_set_initial_state
void System_set_initial_state(SEXP system_xp, Rcpp::NumericVector y, double t0);
RcppExport SEXP _odelia_System_set_initial_state(SEXP system_xpSEXP, SEXP ySEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    System_set_initial_state(system_xp, y, t0);
    return R_NilValue;
END_RCPP
}
// System_reset
void System_reset(SEXP system_xp);
RcppExport SEXP _odelia_System_reset(SEXP system_xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    System_reset(system_xp);
    return R_NilValue;
END_RCPP
}
// System_rates
Rcpp::NumericVector System_rates(SEXP system_xp);
RcppExport SEXP _odelia_System_rates(SEXP system_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(System_rates(system_xp));
    return rcpp_result_gen;
END_RCPP
}
// Solver_new
SEXP Solver_new(SEXP system_xp, SEXP control_xp, bool active);
RcppExport SEXP _odelia_Solver_new(SEXP system_xpSEXP, SEXP control_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_new(system_xp, control_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_reset
void Solver_reset(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_reset(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_reset(solver_xp, active);
    return R_NilValue;
END_RCPP
}
// Solver_time
double Solver_time(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_time(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_time(solver_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_state
Rcpp::NumericVector Solver_state(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_state(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_state(solver_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_times
Rcpp::NumericVector Solver_times(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_times(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_times(solver_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_set_state
void Solver_set_state(SEXP solver_xp, Rcpp::NumericVector y, double time, bool active);
RcppExport SEXP _odelia_Solver_set_state(SEXP solver_xpSEXP, SEXP ySEXP, SEXP timeSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_set_state(solver_xp, y, time, active);
    return R_NilValue;
END_RCPP
}
// Solver_advance_adaptive
void Solver_advance_adaptive(SEXP solver_xp, Rcpp::NumericVector times, bool active);
RcppExport SEXP _odelia_Solver_advance_adaptive(SEXP solver_xpSEXP, SEXP timesSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_advance_adaptive(solver_xp, times, active);
    return R_NilValue;
END_RCPP
}
// Solver_advance_fixed
void Solver_advance_fixed(SEXP solver_xp, Rcpp::NumericVector times, bool active);
RcppExport SEXP _odelia_Solver_advance_fixed(SEXP solver_xpSEXP, SEXP timesSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_advance_fixed(solver_xp, times, active);
    return R_NilValue;
END_RCPP
}
// Solver_step
void Solver_step(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_step(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_step(solver_xp, active);
    return R_NilValue;
END_RCPP
}
// Solver_get_collect
bool Solver_get_collect(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_get_collect(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_get_collect(solver_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_set_collect
void Solver_set_collect(SEXP solver_xp, bool x, bool active);
RcppExport SEXP _odelia_Solver_set_collect(SEXP solver_xpSEXP, SEXP xSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_set_collect(solver_xp, x, active);
    return R_NilValue;
END_RCPP
}
// Solver_get_history_size
std::size_t Solver_get_history_size(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_get_history_size(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_get_history_size(solver_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_get_history_step
Rcpp::DataFrame Solver_get_history_step(SEXP solver_xp, std::size_t i, bool active);
RcppExport SEXP _odelia_Solver_get_history_step(SEXP solver_xpSEXP, SEXP iSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type i(iSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_get_history_step(solver_xp, i, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_get_history
Rcpp::List Solver_get_history(SEXP solver_xp, bool active);
RcppExport SEXP _odelia_Solver_get_history(SEXP solver_xpSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_get_history(solver_xp, active));
    return rcpp_result_gen;
END_RCPP
}
// Solver_set_target
void Solver_set_target(SEXP solver_xp, Rcpp::NumericVector times, Rcpp::NumericMatrix target, Rcpp::IntegerVector obs_indices, bool active);
RcppExport SEXP _odelia_Solver_set_target(SEXP solver_xpSEXP, SEXP timesSEXP, SEXP targetSEXP, SEXP obs_indicesSEXP, SEXP activeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type obs_indices(obs_indicesSEXP);
    Rcpp::traits::input_parameter< bool >::type active(activeSEXP);
    Solver_set_target(solver_xp, times, target, obs_indices, active);
    return R_NilValue;
END_RCPP
}
// Solver_fit
Rcpp::List Solver_fit(SEXP solver_xp, Rcpp::Nullable<Rcpp::NumericVector> ic, Rcpp::Nullable<Rcpp::NumericVector> params);
RcppExport SEXP _odelia_Solver_fit(SEXP solver_xpSEXP, SEXP icSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type solver_xp(solver_xpSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type ic(icSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(Solver_fit(solver_xp, ic, params));
    return rcpp_result_gen;
END_RCPP
}
// lorenz_rhs
List lorenz_rhs(double t, NumericVector state, NumericVector pars);
RcppExport SEXP _odelia_lorenz_rhs(SEXP tSEXP, SEXP stateSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(lorenz_rhs(t, state, pars));
    return rcpp_result_gen;
END_RCPP
}
// test_param_types
Rcpp::List test_param_types(SEXP system_xp);
RcppExport SEXP _odelia_test_param_types(SEXP system_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type system_xp(system_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(test_param_types(system_xp));
    return rcpp_result_gen;
END_RCPP
}
// OdeControl_new
SEXP OdeControl_new();
RcppExport SEXP _odelia_OdeControl_new() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(OdeControl_new());
    return rcpp_result_gen;
END_RCPP
}
// OdeControl_get_controls
Rcpp::List OdeControl_get_controls(SEXP control_xp);
RcppExport SEXP _odelia_OdeControl_get_controls(SEXP control_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(OdeControl_get_controls(control_xp));
    return rcpp_result_gen;
END_RCPP
}
// OdeControl_set_controls
void OdeControl_set_controls(SEXP control_xp, double tol_abs, double tol_rel, double a_y, double a_dydt, double step_size_min, double step_size_max, double step_size_initial);
RcppExport SEXP _odelia_OdeControl_set_controls(SEXP control_xpSEXP, SEXP tol_absSEXP, SEXP tol_relSEXP, SEXP a_ySEXP, SEXP a_dydtSEXP, SEXP step_size_minSEXP, SEXP step_size_maxSEXP, SEXP step_size_initialSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< double >::type a_y(a_ySEXP);
    Rcpp::traits::input_parameter< double >::type a_dydt(a_dydtSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_min(step_size_minSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_max(step_size_maxSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_initial(step_size_initialSEXP);
    OdeControl_set_controls(control_xp, tol_abs, tol_rel, a_y, a_dydt, step_size_min, step_size_max, step_size_initial);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_tol_abs
void OdeControl_set_tol_abs(SEXP control_xp, double tol_abs);
RcppExport SEXP _odelia_OdeControl_set_tol_abs(SEXP control_xpSEXP, SEXP tol_absSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type tol_abs(tol_absSEXP);
    OdeControl_set_tol_abs(control_xp, tol_abs);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_tol_rel
void OdeControl_set_tol_rel(SEXP control_xp, double tol_rel);
RcppExport SEXP _odelia_OdeControl_set_tol_rel(SEXP control_xpSEXP, SEXP tol_relSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type tol_rel(tol_relSEXP);
    OdeControl_set_tol_rel(control_xp, tol_rel);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_a_y
void OdeControl_set_a_y(SEXP control_xp, double a_y);
RcppExport SEXP _odelia_OdeControl_set_a_y(SEXP control_xpSEXP, SEXP a_ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type a_y(a_ySEXP);
    OdeControl_set_a_y(control_xp, a_y);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_a_dydt
void OdeControl_set_a_dydt(SEXP control_xp, double a_dydt);
RcppExport SEXP _odelia_OdeControl_set_a_dydt(SEXP control_xpSEXP, SEXP a_dydtSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type a_dydt(a_dydtSEXP);
    OdeControl_set_a_dydt(control_xp, a_dydt);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_step_size_min
void OdeControl_set_step_size_min(SEXP control_xp, double step_size_min);
RcppExport SEXP _odelia_OdeControl_set_step_size_min(SEXP control_xpSEXP, SEXP step_size_minSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_min(step_size_minSEXP);
    OdeControl_set_step_size_min(control_xp, step_size_min);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_step_size_max
void OdeControl_set_step_size_max(SEXP control_xp, double step_size_max);
RcppExport SEXP _odelia_OdeControl_set_step_size_max(SEXP control_xpSEXP, SEXP step_size_maxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_max(step_size_maxSEXP);
    OdeControl_set_step_size_max(control_xp, step_size_max);
    return R_NilValue;
END_RCPP
}
// OdeControl_set_step_size_initial
void OdeControl_set_step_size_initial(SEXP control_xp, double step_size_initial);
RcppExport SEXP _odelia_OdeControl_set_step_size_initial(SEXP control_xpSEXP, SEXP step_size_initialSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type control_xp(control_xpSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_initial(step_size_initialSEXP);
    OdeControl_set_step_size_initial(control_xp, step_size_initial);
    return R_NilValue;
END_RCPP
}
// Drivers_new
SEXP Drivers_new();
RcppExport SEXP _odelia_Drivers_new() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(Drivers_new());
    return rcpp_result_gen;
END_RCPP
}
// Drivers_set_constant
void Drivers_set_constant(SEXP drivers_xp, std::string driver_name, double k);
RcppExport SEXP _odelia_Drivers_set_constant(SEXP drivers_xpSEXP, SEXP driver_nameSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type driver_name(driver_nameSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Drivers_set_constant(drivers_xp, driver_name, k);
    return R_NilValue;
END_RCPP
}
// Drivers_set_variable
void Drivers_set_variable(SEXP drivers_xp, std::string driver_name, Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _odelia_Drivers_set_variable(SEXP drivers_xpSEXP, SEXP driver_nameSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type driver_name(driver_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Drivers_set_variable(drivers_xp, driver_name, x, y);
    return R_NilValue;
END_RCPP
}
// Drivers_set_extrapolate
void Drivers_set_extrapolate(SEXP drivers_xp, std::string driver_name, bool extrapolate);
RcppExport SEXP _odelia_Drivers_set_extrapolate(SEXP drivers_xpSEXP, SEXP driver_nameSEXP, SEXP extrapolateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type driver_name(driver_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type extrapolate(extrapolateSEXP);
    Drivers_set_extrapolate(drivers_xp, driver_name, extrapolate);
    return R_NilValue;
END_RCPP
}
// Drivers_evaluate
double Drivers_evaluate(SEXP drivers_xp, std::string driver_name, double x);
RcppExport SEXP _odelia_Drivers_evaluate(SEXP drivers_xpSEXP, SEXP driver_nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type driver_name(driver_nameSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Drivers_evaluate(drivers_xp, driver_name, x));
    return rcpp_result_gen;
END_RCPP
}
// Drivers_evaluate_range
Rcpp::NumericVector Drivers_evaluate_range(SEXP drivers_xp, std::string driver_name, Rcpp::NumericVector x);
RcppExport SEXP _odelia_Drivers_evaluate_range(SEXP drivers_xpSEXP, SEXP driver_nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type driver_name(driver_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Drivers_evaluate_range(drivers_xp, driver_name, x));
    return rcpp_result_gen;
END_RCPP
}
// Drivers_get_names
Rcpp::CharacterVector Drivers_get_names(SEXP drivers_xp);
RcppExport SEXP _odelia_Drivers_get_names(SEXP drivers_xpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    rcpp_result_gen = Rcpp::wrap(Drivers_get_names(drivers_xp));
    return rcpp_result_gen;
END_RCPP
}
// Drivers_clear
void Drivers_clear(SEXP drivers_xp);
RcppExport SEXP _odelia_Drivers_clear(SEXP drivers_xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type drivers_xp(drivers_xpSEXP);
    Drivers_clear(drivers_xp);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_odelia_System_new", (DL_FUNC) &_odelia_System_new, 3},
    {"_odelia_System_pars", (DL_FUNC) &_odelia_System_pars, 1},
    {"_odelia_System_set_params", (DL_FUNC) &_odelia_System_set_params, 2},
    {"_odelia_System_set_state", (DL_FUNC) &_odelia_System_set_state, 3},
    {"_odelia_System_state", (DL_FUNC) &_odelia_System_state, 1},
    {"_odelia_System_set_initial_state", (DL_FUNC) &_odelia_System_set_initial_state, 3},
    {"_odelia_System_reset", (DL_FUNC) &_odelia_System_reset, 1},
    {"_odelia_System_rates", (DL_FUNC) &_odelia_System_rates, 1},
    {"_odelia_Solver_new", (DL_FUNC) &_odelia_Solver_new, 3},
    {"_odelia_Solver_reset", (DL_FUNC) &_odelia_Solver_reset, 2},
    {"_odelia_Solver_time", (DL_FUNC) &_odelia_Solver_time, 2},
    {"_odelia_Solver_state", (DL_FUNC) &_odelia_Solver_state, 2},
    {"_odelia_Solver_times", (DL_FUNC) &_odelia_Solver_times, 2},
    {"_odelia_Solver_set_state", (DL_FUNC) &_odelia_Solver_set_state, 4},
    {"_odelia_Solver_advance_adaptive", (DL_FUNC) &_odelia_Solver_advance_adaptive, 3},
    {"_odelia_Solver_advance_fixed", (DL_FUNC) &_odelia_Solver_advance_fixed, 3},
    {"_odelia_Solver_step", (DL_FUNC) &_odelia_Solver_step, 2},
    {"_odelia_Solver_get_collect", (DL_FUNC) &_odelia_Solver_get_collect, 2},
    {"_odelia_Solver_set_collect", (DL_FUNC) &_odelia_Solver_set_collect, 3},
    {"_odelia_Solver_get_history_size", (DL_FUNC) &_odelia_Solver_get_history_size, 2},
    {"_odelia_Solver_get_history_step", (DL_FUNC) &_odelia_Solver_get_history_step, 3},
    {"_odelia_Solver_get_history", (DL_FUNC) &_odelia_Solver_get_history, 2},
    {"_odelia_Solver_set_target", (DL_FUNC) &_odelia_Solver_set_target, 5},
    {"_odelia_Solver_fit", (DL_FUNC) &_odelia_Solver_fit, 3},
    {"_odelia_lorenz_rhs", (DL_FUNC) &_odelia_lorenz_rhs, 3},
    {"_odelia_test_param_types", (DL_FUNC) &_odelia_test_param_types, 1},
    {"_odelia_OdeControl_new", (DL_FUNC) &_odelia_OdeControl_new, 0},
    {"_odelia_OdeControl_get_controls", (DL_FUNC) &_odelia_OdeControl_get_controls, 1},
    {"_odelia_OdeControl_set_controls", (DL_FUNC) &_odelia_OdeControl_set_controls, 8},
    {"_odelia_OdeControl_set_tol_abs", (DL_FUNC) &_odelia_OdeControl_set_tol_abs, 2},
    {"_odelia_OdeControl_set_tol_rel", (DL_FUNC) &_odelia_OdeControl_set_tol_rel, 2},
    {"_odelia_OdeControl_set_a_y", (DL_FUNC) &_odelia_OdeControl_set_a_y, 2},
    {"_odelia_OdeControl_set_a_dydt", (DL_FUNC) &_odelia_OdeControl_set_a_dydt, 2},
    {"_odelia_OdeControl_set_step_size_min", (DL_FUNC) &_odelia_OdeControl_set_step_size_min, 2},
    {"_odelia_OdeControl_set_step_size_max", (DL_FUNC) &_odelia_OdeControl_set_step_size_max, 2},
    {"_odelia_OdeControl_set_step_size_initial", (DL_FUNC) &_odelia_OdeControl_set_step_size_initial, 2},
    {"_odelia_Drivers_new", (DL_FUNC) &_odelia_Drivers_new, 0},
    {"_odelia_Drivers_set_constant", (DL_FUNC) &_odelia_Drivers_set_constant, 3},
    {"_odelia_Drivers_set_variable", (DL_FUNC) &_odelia_Drivers_set_variable, 4},
    {"_odelia_Drivers_set_extrapolate", (DL_FUNC) &_odelia_Drivers_set_extrapolate, 3},
    {"_odelia_Drivers_evaluate", (DL_FUNC) &_odelia_Drivers_evaluate, 3},
    {"_odelia_Drivers_evaluate_range", (DL_FUNC) &_odelia_Drivers_evaluate_range, 3},
    {"_odelia_Drivers_get_names", (DL_FUNC) &_odelia_Drivers_get_names, 1},
    {"_odelia_Drivers_clear", (DL_FUNC) &_odelia_Drivers_clear, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_odelia(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
