// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/plant.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Lorenz__ctor
plant::ode::test::Lorenz Lorenz__ctor(double sigma, double R, double b);
RcppExport SEXP _plant_Lorenz__ctor(SEXP sigmaSEXP, SEXP RSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(Lorenz__ctor(sigma, R, b));
    return rcpp_result_gen;
END_RCPP
}
// Lorenz__ode_size__get
size_t Lorenz__ode_size__get(plant::RcppR6::RcppR6<plant::ode::test::Lorenz> obj_);
RcppExport SEXP _plant_Lorenz__ode_size__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::test::Lorenz> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(Lorenz__ode_size__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// Lorenz__ode_state__get
plant::ode::state_type Lorenz__ode_state__get(plant::RcppR6::RcppR6<plant::ode::test::Lorenz> obj_);
RcppExport SEXP _plant_Lorenz__ode_state__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::test::Lorenz> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(Lorenz__ode_state__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// Lorenz__ode_state__set
void Lorenz__ode_state__set(plant::RcppR6::RcppR6<plant::ode::test::Lorenz> obj_, plant::ode::state_type value);
RcppExport SEXP _plant_Lorenz__ode_state__set(SEXP obj_SEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::test::Lorenz> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< plant::ode::state_type >::type value(valueSEXP);
    Lorenz__ode_state__set(obj_, value);
    return R_NilValue;
END_RCPP
}
// Lorenz__ode_rates__get
plant::ode::state_type Lorenz__ode_rates__get(plant::RcppR6::RcppR6<plant::ode::test::Lorenz> obj_);
RcppExport SEXP _plant_Lorenz__ode_rates__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::test::Lorenz> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(Lorenz__ode_rates__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// Lorenz__pars__get
std::vector<double> Lorenz__pars__get(plant::RcppR6::RcppR6<plant::ode::test::Lorenz> obj_);
RcppExport SEXP _plant_Lorenz__pars__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::test::Lorenz> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(Lorenz__pars__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeR__ctor
plant::ode::test::OdeR OdeR__ctor(Rcpp::Function derivs, Rcpp::Function state, double time);
RcppExport SEXP _plant_OdeR__ctor(SEXP derivsSEXP, SEXP stateSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type state(stateSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(OdeR__ctor(derivs, state, time));
    return rcpp_result_gen;
END_RCPP
}
// OdeR__update_state
void OdeR__update_state(plant::RcppR6::RcppR6<plant::ode::test::OdeR> obj_);
RcppExport SEXP _plant_OdeR__update_state(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::test::OdeR> >::type obj_(obj_SEXP);
    OdeR__update_state(obj_);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__ctor
plant::ode::Runner<plant::ode::test::Lorenz> OdeRunner___Lorenz__ctor(plant::ode::test::Lorenz obj, plant::ode::OdeControl control);
RcppExport SEXP _plant_OdeRunner___Lorenz__ctor(SEXP objSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::ode::test::Lorenz >::type obj(objSEXP);
    Rcpp::traits::input_parameter< plant::ode::OdeControl >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___Lorenz__ctor(obj, control));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___Lorenz__advance_adaptive
void OdeRunner___Lorenz__advance_adaptive(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_, double time);
RcppExport SEXP _plant_OdeRunner___Lorenz__advance_adaptive(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    OdeRunner___Lorenz__advance_adaptive(obj_, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__advance_fixed
void OdeRunner___Lorenz__advance_fixed(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_, std::vector<double> time);
RcppExport SEXP _plant_OdeRunner___Lorenz__advance_fixed(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type time(timeSEXP);
    OdeRunner___Lorenz__advance_fixed(obj_, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__step
void OdeRunner___Lorenz__step(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_);
RcppExport SEXP _plant_OdeRunner___Lorenz__step(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    OdeRunner___Lorenz__step(obj_);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__step_to
void OdeRunner___Lorenz__step_to(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_, double time);
RcppExport SEXP _plant_OdeRunner___Lorenz__step_to(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    OdeRunner___Lorenz__step_to(obj_, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__set_state
void OdeRunner___Lorenz__set_state(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_, plant::ode::state_type y, double time);
RcppExport SEXP _plant_OdeRunner___Lorenz__set_state(SEXP obj_SEXP, SEXP ySEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< plant::ode::state_type >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    OdeRunner___Lorenz__set_state(obj_, y, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__set_state_from_system
void OdeRunner___Lorenz__set_state_from_system(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_);
RcppExport SEXP _plant_OdeRunner___Lorenz__set_state_from_system(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    OdeRunner___Lorenz__set_state_from_system(obj_);
    return R_NilValue;
END_RCPP
}
// OdeRunner___Lorenz__time__get
double OdeRunner___Lorenz__time__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_);
RcppExport SEXP _plant_OdeRunner___Lorenz__time__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___Lorenz__time__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___Lorenz__state__get
plant::ode::state_type OdeRunner___Lorenz__state__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_);
RcppExport SEXP _plant_OdeRunner___Lorenz__state__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___Lorenz__state__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___Lorenz__times__get
std::vector<double> OdeRunner___Lorenz__times__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_);
RcppExport SEXP _plant_OdeRunner___Lorenz__times__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___Lorenz__times__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___Lorenz__object__get
plant::ode::test::Lorenz OdeRunner___Lorenz__object__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > obj_);
RcppExport SEXP _plant_OdeRunner___Lorenz__object__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::Lorenz> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___Lorenz__object__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___OdeR__ctor
plant::ode::Runner<plant::ode::test::OdeR> OdeRunner___OdeR__ctor(plant::ode::test::OdeR obj, plant::ode::OdeControl control);
RcppExport SEXP _plant_OdeRunner___OdeR__ctor(SEXP objSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::ode::test::OdeR >::type obj(objSEXP);
    Rcpp::traits::input_parameter< plant::ode::OdeControl >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___OdeR__ctor(obj, control));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___OdeR__advance_adaptive
void OdeRunner___OdeR__advance_adaptive(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_, double time);
RcppExport SEXP _plant_OdeRunner___OdeR__advance_adaptive(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    OdeRunner___OdeR__advance_adaptive(obj_, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___OdeR__advance_fixed
void OdeRunner___OdeR__advance_fixed(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_, std::vector<double> time);
RcppExport SEXP _plant_OdeRunner___OdeR__advance_fixed(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type time(timeSEXP);
    OdeRunner___OdeR__advance_fixed(obj_, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___OdeR__step
void OdeRunner___OdeR__step(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_);
RcppExport SEXP _plant_OdeRunner___OdeR__step(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    OdeRunner___OdeR__step(obj_);
    return R_NilValue;
END_RCPP
}
// OdeRunner___OdeR__step_to
void OdeRunner___OdeR__step_to(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_, double time);
RcppExport SEXP _plant_OdeRunner___OdeR__step_to(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    OdeRunner___OdeR__step_to(obj_, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___OdeR__set_state
void OdeRunner___OdeR__set_state(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_, plant::ode::state_type y, double time);
RcppExport SEXP _plant_OdeRunner___OdeR__set_state(SEXP obj_SEXP, SEXP ySEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< plant::ode::state_type >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    OdeRunner___OdeR__set_state(obj_, y, time);
    return R_NilValue;
END_RCPP
}
// OdeRunner___OdeR__set_state_from_system
void OdeRunner___OdeR__set_state_from_system(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_);
RcppExport SEXP _plant_OdeRunner___OdeR__set_state_from_system(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    OdeRunner___OdeR__set_state_from_system(obj_);
    return R_NilValue;
END_RCPP
}
// OdeRunner___OdeR__time__get
double OdeRunner___OdeR__time__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_);
RcppExport SEXP _plant_OdeRunner___OdeR__time__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___OdeR__time__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___OdeR__state__get
plant::ode::state_type OdeRunner___OdeR__state__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_);
RcppExport SEXP _plant_OdeRunner___OdeR__state__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___OdeR__state__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___OdeR__times__get
std::vector<double> OdeRunner___OdeR__times__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_);
RcppExport SEXP _plant_OdeRunner___OdeR__times__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___OdeR__times__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeRunner___OdeR__object__get
plant::ode::test::OdeR OdeRunner___OdeR__object__get(plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > obj_);
RcppExport SEXP _plant_OdeRunner___OdeR__object__get(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< plant::RcppR6::RcppR6<plant::ode::Runner<plant::ode::test::OdeR> > >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(OdeRunner___OdeR__object__get(obj_));
    return rcpp_result_gen;
END_RCPP
}
// OdeControl__ctor
SEXP OdeControl__ctor();
RcppExport SEXP _plant_OdeControl__ctor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(OdeControl__ctor());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plant_Lorenz__ctor", (DL_FUNC) &_plant_Lorenz__ctor, 3},
    {"_plant_Lorenz__ode_size__get", (DL_FUNC) &_plant_Lorenz__ode_size__get, 1},
    {"_plant_Lorenz__ode_state__get", (DL_FUNC) &_plant_Lorenz__ode_state__get, 1},
    {"_plant_Lorenz__ode_state__set", (DL_FUNC) &_plant_Lorenz__ode_state__set, 2},
    {"_plant_Lorenz__ode_rates__get", (DL_FUNC) &_plant_Lorenz__ode_rates__get, 1},
    {"_plant_Lorenz__pars__get", (DL_FUNC) &_plant_Lorenz__pars__get, 1},
    {"_plant_OdeR__ctor", (DL_FUNC) &_plant_OdeR__ctor, 3},
    {"_plant_OdeR__update_state", (DL_FUNC) &_plant_OdeR__update_state, 1},
    {"_plant_OdeRunner___Lorenz__ctor", (DL_FUNC) &_plant_OdeRunner___Lorenz__ctor, 2},
    {"_plant_OdeRunner___Lorenz__advance_adaptive", (DL_FUNC) &_plant_OdeRunner___Lorenz__advance_adaptive, 2},
    {"_plant_OdeRunner___Lorenz__advance_fixed", (DL_FUNC) &_plant_OdeRunner___Lorenz__advance_fixed, 2},
    {"_plant_OdeRunner___Lorenz__step", (DL_FUNC) &_plant_OdeRunner___Lorenz__step, 1},
    {"_plant_OdeRunner___Lorenz__step_to", (DL_FUNC) &_plant_OdeRunner___Lorenz__step_to, 2},
    {"_plant_OdeRunner___Lorenz__set_state", (DL_FUNC) &_plant_OdeRunner___Lorenz__set_state, 3},
    {"_plant_OdeRunner___Lorenz__set_state_from_system", (DL_FUNC) &_plant_OdeRunner___Lorenz__set_state_from_system, 1},
    {"_plant_OdeRunner___Lorenz__time__get", (DL_FUNC) &_plant_OdeRunner___Lorenz__time__get, 1},
    {"_plant_OdeRunner___Lorenz__state__get", (DL_FUNC) &_plant_OdeRunner___Lorenz__state__get, 1},
    {"_plant_OdeRunner___Lorenz__times__get", (DL_FUNC) &_plant_OdeRunner___Lorenz__times__get, 1},
    {"_plant_OdeRunner___Lorenz__object__get", (DL_FUNC) &_plant_OdeRunner___Lorenz__object__get, 1},
    {"_plant_OdeRunner___OdeR__ctor", (DL_FUNC) &_plant_OdeRunner___OdeR__ctor, 2},
    {"_plant_OdeRunner___OdeR__advance_adaptive", (DL_FUNC) &_plant_OdeRunner___OdeR__advance_adaptive, 2},
    {"_plant_OdeRunner___OdeR__advance_fixed", (DL_FUNC) &_plant_OdeRunner___OdeR__advance_fixed, 2},
    {"_plant_OdeRunner___OdeR__step", (DL_FUNC) &_plant_OdeRunner___OdeR__step, 1},
    {"_plant_OdeRunner___OdeR__step_to", (DL_FUNC) &_plant_OdeRunner___OdeR__step_to, 2},
    {"_plant_OdeRunner___OdeR__set_state", (DL_FUNC) &_plant_OdeRunner___OdeR__set_state, 3},
    {"_plant_OdeRunner___OdeR__set_state_from_system", (DL_FUNC) &_plant_OdeRunner___OdeR__set_state_from_system, 1},
    {"_plant_OdeRunner___OdeR__time__get", (DL_FUNC) &_plant_OdeRunner___OdeR__time__get, 1},
    {"_plant_OdeRunner___OdeR__state__get", (DL_FUNC) &_plant_OdeRunner___OdeR__state__get, 1},
    {"_plant_OdeRunner___OdeR__times__get", (DL_FUNC) &_plant_OdeRunner___OdeR__times__get, 1},
    {"_plant_OdeRunner___OdeR__object__get", (DL_FUNC) &_plant_OdeRunner___OdeR__object__get, 1},
    {"_plant_OdeControl__ctor", (DL_FUNC) &_plant_OdeControl__ctor, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_plant(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
