## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: 0b53d9386dbd4482a071923c1344aae0

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib plant
NULL

## This section of code is only included where templated classes are
## included.  Don't rely on the approach taken here, as it may change
## soon.
check_type <- function(type, valid) {
  i <- match(list(type), valid, nomatch=NA)
  if (is.na(i)) {
    choices <- paste(sprintf("\t%s", sapply(valid, paste, collapse=", ")),
                     collapse="\n")
    stop(sprintf("Invalid type '%s'; expected one of:\n%s",
                 paste(type, collapse=", "), choices))
  }
  names(valid)[[i]]
}


`Lorenz` <- function(sigma, R, b) {
  Lorenz__ctor(sigma, R, b)
}
.R6_Lorenz <-
  R6::R6Class(
    "Lorenz",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      }),
    active=list(
      ode_size = function(value) {
        if (missing(value)) {
          Lorenz__ode_size__get(self)
        } else {
          stop("Lorenz$ode_size is read-only")
        }
      },
      ode_state = function(value) {
        if (missing(value)) {
          Lorenz__ode_state__get(self)
        } else {
          Lorenz__ode_state__set(self, value)
        }
      },
      ode_rates = function(value) {
        if (missing(value)) {
          Lorenz__ode_rates__get(self)
        } else {
          stop("Lorenz$ode_rates is read-only")
        }
      },
      pars = function(value) {
        if (missing(value)) {
          Lorenz__pars__get(self)
        } else {
          stop("Lorenz$pars is read-only")
        }
      }))


`OdeR` <- function(derivs, state, time) {
  OdeR__ctor(derivs, state, time)
}
.R6_OdeR <-
  R6::R6Class(
    "OdeR",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      update_state = function() {
        OdeR__update_state(self)
      }),
    active=list())

OdeRunner <- function(T) {
  type <- c(T)
  valid <- list("OdeRunner<Lorenz>"="Lorenz", "OdeRunner<OdeR>"="OdeR")
  constructors <- list("OdeRunner<Lorenz>"=`OdeRunner<Lorenz>`, "OdeRunner<OdeR>"=`OdeRunner<OdeR>`)
  constructors[[check_type(type, valid)]]
}
.R6_OdeRunner <- R6::R6Class("OdeRunner")



`OdeRunner<Lorenz>` <- function(obj, control=OdeControl()) {
  OdeRunner___Lorenz__ctor(obj, control)
}
.R6_OdeRunner___Lorenz <-
  R6::R6Class(
    "OdeRunner<Lorenz>",
    inherit=.R6_OdeRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      advance_adaptive = function(time) {
        OdeRunner___Lorenz__advance_adaptive(self, time)
      },
      advance_fixed = function(time) {
        OdeRunner___Lorenz__advance_fixed(self, time)
      },
      step = function() {
        OdeRunner___Lorenz__step(self)
      },
      step_to = function(time) {
        OdeRunner___Lorenz__step_to(self, time)
      },
      set_state = function(y, time) {
        OdeRunner___Lorenz__set_state(self, y, time)
      },
      set_state_from_system = function() {
        OdeRunner___Lorenz__set_state_from_system(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__time__get(self)
        } else {
          stop("OdeRunner<Lorenz>$time is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__state__get(self)
        } else {
          stop("OdeRunner<Lorenz>$state is read-only")
        }
      },
      times = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__times__get(self)
        } else {
          stop("OdeRunner<Lorenz>$times is read-only")
        }
      },
      object = function(value) {
        if (missing(value)) {
          OdeRunner___Lorenz__object__get(self)
        } else {
          stop("OdeRunner<Lorenz>$object is read-only")
        }
      }))


`OdeRunner<OdeR>` <- function(obj, control=OdeControl()) {
  OdeRunner___OdeR__ctor(obj, control)
}
.R6_OdeRunner___OdeR <-
  R6::R6Class(
    "OdeRunner<OdeR>",
    inherit=.R6_OdeRunner,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      advance_adaptive = function(time) {
        OdeRunner___OdeR__advance_adaptive(self, time)
      },
      advance_fixed = function(time) {
        OdeRunner___OdeR__advance_fixed(self, time)
      },
      step = function() {
        OdeRunner___OdeR__step(self)
      },
      step_to = function(time) {
        OdeRunner___OdeR__step_to(self, time)
      },
      set_state = function(y, time) {
        OdeRunner___OdeR__set_state(self, y, time)
      },
      set_state_from_system = function() {
        OdeRunner___OdeR__set_state_from_system(self)
      }),
    active=list(
      time = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__time__get(self)
        } else {
          stop("OdeRunner<OdeR>$time is read-only")
        }
      },
      state = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__state__get(self)
        } else {
          stop("OdeRunner<OdeR>$state is read-only")
        }
      },
      times = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__times__get(self)
        } else {
          stop("OdeRunner<OdeR>$times is read-only")
        }
      },
      object = function(value) {
        if (missing(value)) {
          OdeRunner___OdeR__object__get(self)
        } else {
          stop("OdeRunner<OdeR>$object is read-only")
        }
      }))

##' Control parameters for the ode system
##' @title ODE Control parameters
##' @param ...,values Values to initialise the struct with (either as
##' variadic arguments, or as a list, but not both).
`OdeControl` <- function(..., values=list(...)) {
  ret <- OdeControl__ctor()
  if (length(values) > 0L) {
    if (is.null(names(values)) || any(names(values) == "")) {
      stop("All values must be named")
    }
    if (length(err <- setdiff(names(values), names(ret))) > 0L) {
      stop(sprintf("Unknown fields: %s", paste(err, collapse=", ")))
    }
    to_set <- intersect(names(values), names(ret))
    ret[to_set] <- values[to_set]
  }
  ret
}


