# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Lorenz__ctor <- function(sigma, R, b) {
    .Call('_plant_Lorenz__ctor', PACKAGE = 'plant', sigma, R, b)
}

Lorenz__ode_size__get <- function(obj_) {
    .Call('_plant_Lorenz__ode_size__get', PACKAGE = 'plant', obj_)
}

Lorenz__ode_state__get <- function(obj_) {
    .Call('_plant_Lorenz__ode_state__get', PACKAGE = 'plant', obj_)
}

Lorenz__ode_state__set <- function(obj_, value) {
    invisible(.Call('_plant_Lorenz__ode_state__set', PACKAGE = 'plant', obj_, value))
}

Lorenz__ode_rates__get <- function(obj_) {
    .Call('_plant_Lorenz__ode_rates__get', PACKAGE = 'plant', obj_)
}

Lorenz__pars__get <- function(obj_) {
    .Call('_plant_Lorenz__pars__get', PACKAGE = 'plant', obj_)
}

OdeR__ctor <- function(derivs, state, time) {
    .Call('_plant_OdeR__ctor', PACKAGE = 'plant', derivs, state, time)
}

OdeR__update_state <- function(obj_) {
    invisible(.Call('_plant_OdeR__update_state', PACKAGE = 'plant', obj_))
}

OdeRunner___Lorenz__ctor <- function(obj, control) {
    .Call('_plant_OdeRunner___Lorenz__ctor', PACKAGE = 'plant', obj, control)
}

OdeRunner___Lorenz__advance_adaptive <- function(obj_, time) {
    invisible(.Call('_plant_OdeRunner___Lorenz__advance_adaptive', PACKAGE = 'plant', obj_, time))
}

OdeRunner___Lorenz__advance_fixed <- function(obj_, time) {
    invisible(.Call('_plant_OdeRunner___Lorenz__advance_fixed', PACKAGE = 'plant', obj_, time))
}

OdeRunner___Lorenz__step <- function(obj_) {
    invisible(.Call('_plant_OdeRunner___Lorenz__step', PACKAGE = 'plant', obj_))
}

OdeRunner___Lorenz__step_to <- function(obj_, time) {
    invisible(.Call('_plant_OdeRunner___Lorenz__step_to', PACKAGE = 'plant', obj_, time))
}

OdeRunner___Lorenz__set_state <- function(obj_, y, time) {
    invisible(.Call('_plant_OdeRunner___Lorenz__set_state', PACKAGE = 'plant', obj_, y, time))
}

OdeRunner___Lorenz__set_state_from_system <- function(obj_) {
    invisible(.Call('_plant_OdeRunner___Lorenz__set_state_from_system', PACKAGE = 'plant', obj_))
}

OdeRunner___Lorenz__time__get <- function(obj_) {
    .Call('_plant_OdeRunner___Lorenz__time__get', PACKAGE = 'plant', obj_)
}

OdeRunner___Lorenz__state__get <- function(obj_) {
    .Call('_plant_OdeRunner___Lorenz__state__get', PACKAGE = 'plant', obj_)
}

OdeRunner___Lorenz__times__get <- function(obj_) {
    .Call('_plant_OdeRunner___Lorenz__times__get', PACKAGE = 'plant', obj_)
}

OdeRunner___Lorenz__object__get <- function(obj_) {
    .Call('_plant_OdeRunner___Lorenz__object__get', PACKAGE = 'plant', obj_)
}

OdeRunner___OdeR__ctor <- function(obj, control) {
    .Call('_plant_OdeRunner___OdeR__ctor', PACKAGE = 'plant', obj, control)
}

OdeRunner___OdeR__advance_adaptive <- function(obj_, time) {
    invisible(.Call('_plant_OdeRunner___OdeR__advance_adaptive', PACKAGE = 'plant', obj_, time))
}

OdeRunner___OdeR__advance_fixed <- function(obj_, time) {
    invisible(.Call('_plant_OdeRunner___OdeR__advance_fixed', PACKAGE = 'plant', obj_, time))
}

OdeRunner___OdeR__step <- function(obj_) {
    invisible(.Call('_plant_OdeRunner___OdeR__step', PACKAGE = 'plant', obj_))
}

OdeRunner___OdeR__step_to <- function(obj_, time) {
    invisible(.Call('_plant_OdeRunner___OdeR__step_to', PACKAGE = 'plant', obj_, time))
}

OdeRunner___OdeR__set_state <- function(obj_, y, time) {
    invisible(.Call('_plant_OdeRunner___OdeR__set_state', PACKAGE = 'plant', obj_, y, time))
}

OdeRunner___OdeR__set_state_from_system <- function(obj_) {
    invisible(.Call('_plant_OdeRunner___OdeR__set_state_from_system', PACKAGE = 'plant', obj_))
}

OdeRunner___OdeR__time__get <- function(obj_) {
    .Call('_plant_OdeRunner___OdeR__time__get', PACKAGE = 'plant', obj_)
}

OdeRunner___OdeR__state__get <- function(obj_) {
    .Call('_plant_OdeRunner___OdeR__state__get', PACKAGE = 'plant', obj_)
}

OdeRunner___OdeR__times__get <- function(obj_) {
    .Call('_plant_OdeRunner___OdeR__times__get', PACKAGE = 'plant', obj_)
}

OdeRunner___OdeR__object__get <- function(obj_) {
    .Call('_plant_OdeRunner___OdeR__object__get', PACKAGE = 'plant', obj_)
}

OdeControl__ctor <- function() {
    .Call('_plant_OdeControl__ctor', PACKAGE = 'plant')
}

