# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

System_new <- function(sigma, R, b) {
    .Call(`_odelia_System_new`, sigma, R, b)
}

System_pars <- function(system_xp) {
    .Call(`_odelia_System_pars`, system_xp)
}

System_set_params <- function(system_xp, params) {
    invisible(.Call(`_odelia_System_set_params`, system_xp, params))
}

System_set_state <- function(system_xp, y, time) {
    invisible(.Call(`_odelia_System_set_state`, system_xp, y, time))
}

System_state <- function(system_xp) {
    .Call(`_odelia_System_state`, system_xp)
}

System_set_initial_state <- function(system_xp, y, t0 = 0.0) {
    invisible(.Call(`_odelia_System_set_initial_state`, system_xp, y, t0))
}

System_reset <- function(system_xp) {
    invisible(.Call(`_odelia_System_reset`, system_xp))
}

System_rates <- function(system_xp) {
    .Call(`_odelia_System_rates`, system_xp)
}

Solver_new <- function(system_xp, control_xp, active = FALSE) {
    .Call(`_odelia_Solver_new`, system_xp, control_xp, active)
}

Solver_reset <- function(solver_xp, active = FALSE) {
    invisible(.Call(`_odelia_Solver_reset`, solver_xp, active))
}

Solver_time <- function(solver_xp, active = FALSE) {
    .Call(`_odelia_Solver_time`, solver_xp, active)
}

Solver_state <- function(solver_xp, active = FALSE) {
    .Call(`_odelia_Solver_state`, solver_xp, active)
}

Solver_times <- function(solver_xp, active = FALSE) {
    .Call(`_odelia_Solver_times`, solver_xp, active)
}

Solver_set_state <- function(solver_xp, y, time, active = FALSE) {
    invisible(.Call(`_odelia_Solver_set_state`, solver_xp, y, time, active))
}

Solver_advance_adaptive <- function(solver_xp, times, active = FALSE) {
    invisible(.Call(`_odelia_Solver_advance_adaptive`, solver_xp, times, active))
}

Solver_advance_fixed <- function(solver_xp, times, active = FALSE) {
    invisible(.Call(`_odelia_Solver_advance_fixed`, solver_xp, times, active))
}

Solver_step <- function(solver_xp, active = FALSE) {
    invisible(.Call(`_odelia_Solver_step`, solver_xp, active))
}

Solver_get_collect <- function(solver_xp, active = FALSE) {
    .Call(`_odelia_Solver_get_collect`, solver_xp, active)
}

Solver_set_collect <- function(solver_xp, x, active = FALSE) {
    invisible(.Call(`_odelia_Solver_set_collect`, solver_xp, x, active))
}

Solver_get_history_size <- function(solver_xp, active = FALSE) {
    .Call(`_odelia_Solver_get_history_size`, solver_xp, active)
}

Solver_get_history_step <- function(solver_xp, i, active = FALSE) {
    .Call(`_odelia_Solver_get_history_step`, solver_xp, i, active)
}

Solver_get_history <- function(solver_xp, active = FALSE) {
    .Call(`_odelia_Solver_get_history`, solver_xp, active)
}

Solver_set_target <- function(solver_xp, times, target, obs_indices, active = FALSE) {
    invisible(.Call(`_odelia_Solver_set_target`, solver_xp, times, target, obs_indices, active))
}

Solver_fit <- function(solver_xp, ic = NULL, params = NULL) {
    .Call(`_odelia_Solver_fit`, solver_xp, ic, params)
}

lorenz_rhs <- function(t, state, pars) {
    .Call(`_odelia_lorenz_rhs`, t, state, pars)
}

test_param_types <- function(system_xp) {
    .Call(`_odelia_test_param_types`, system_xp)
}

OdeControl_new <- function() {
    .Call(`_odelia_OdeControl_new`)
}

OdeControl_get_controls <- function(control_xp) {
    .Call(`_odelia_OdeControl_get_controls`, control_xp)
}

OdeControl_set_controls <- function(control_xp, tol_abs, tol_rel, a_y, a_dydt, step_size_min, step_size_max, step_size_initial) {
    invisible(.Call(`_odelia_OdeControl_set_controls`, control_xp, tol_abs, tol_rel, a_y, a_dydt, step_size_min, step_size_max, step_size_initial))
}

OdeControl_set_tol_abs <- function(control_xp, tol_abs) {
    invisible(.Call(`_odelia_OdeControl_set_tol_abs`, control_xp, tol_abs))
}

OdeControl_set_tol_rel <- function(control_xp, tol_rel) {
    invisible(.Call(`_odelia_OdeControl_set_tol_rel`, control_xp, tol_rel))
}

OdeControl_set_a_y <- function(control_xp, a_y) {
    invisible(.Call(`_odelia_OdeControl_set_a_y`, control_xp, a_y))
}

OdeControl_set_a_dydt <- function(control_xp, a_dydt) {
    invisible(.Call(`_odelia_OdeControl_set_a_dydt`, control_xp, a_dydt))
}

OdeControl_set_step_size_min <- function(control_xp, step_size_min) {
    invisible(.Call(`_odelia_OdeControl_set_step_size_min`, control_xp, step_size_min))
}

OdeControl_set_step_size_max <- function(control_xp, step_size_max) {
    invisible(.Call(`_odelia_OdeControl_set_step_size_max`, control_xp, step_size_max))
}

OdeControl_set_step_size_initial <- function(control_xp, step_size_initial) {
    invisible(.Call(`_odelia_OdeControl_set_step_size_initial`, control_xp, step_size_initial))
}

Drivers_new <- function() {
    .Call(`_odelia_Drivers_new`)
}

Drivers_set_constant <- function(drivers_xp, driver_name, k) {
    invisible(.Call(`_odelia_Drivers_set_constant`, drivers_xp, driver_name, k))
}

Drivers_set_variable <- function(drivers_xp, driver_name, x, y) {
    invisible(.Call(`_odelia_Drivers_set_variable`, drivers_xp, driver_name, x, y))
}

Drivers_set_extrapolate <- function(drivers_xp, driver_name, extrapolate) {
    invisible(.Call(`_odelia_Drivers_set_extrapolate`, drivers_xp, driver_name, extrapolate))
}

Drivers_evaluate <- function(drivers_xp, driver_name, x) {
    .Call(`_odelia_Drivers_evaluate`, drivers_xp, driver_name, x)
}

Drivers_evaluate_range <- function(drivers_xp, driver_name, x) {
    .Call(`_odelia_Drivers_evaluate_range`, drivers_xp, driver_name, x)
}

Drivers_get_names <- function(drivers_xp) {
    .Call(`_odelia_Drivers_get_names`, drivers_xp)
}

Drivers_clear <- function(drivers_xp) {
    invisible(.Call(`_odelia_Drivers_clear`, drivers_xp))
}

parabola_eval <- function(params) {
    .Call(`_odelia_parabola_eval`, params)
}

